name: Security Check
on:
  push:
    branches:
      - 'main'

jobs:
  Docker:
    name: Docker Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan Dockerfile for Policy Violation (Table Format)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'file'  
          format: 'table'
          output: 'trivy-results.table'
