name: DefectDojo-Gitleaks
on: [pull_request, push, workflow_dispatch]

jobs:
  gitleaks_scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.2
        with:
          flags: "--all"

  defectdojo_scan:
    name: DefectDojo Scan
    runs-on: ubuntu-latest
    needs: gitleaks_scan
    steps:
      - name: Upload Gitleaks Results to DefectDojo
        run: |
          curl -X POST \
            'http://20.203.119.59/api/v2/reimport-scan/' \
            -H 'accept: application/json' \
            -H 'Content-Type: multipart/form-data' \
            -H 'Authorization: Token d35b7ccf20b2d88408b7cb6bdd3211419dca4095' \
            -H 'X-CSRFToken: cgpwJyENocfovvV5wao18wmakV9LyWx2lmGhvP4seagvnIymdjlj9ooiv6pLe8NI' \
            -F 'file=@result.json;type=application/json' \
            -F 'minimum_severity=Info' \
            -F 'active=true' \
            -F 'verified=true' \
            -F 'do_not_reactivate=true' \
            -F 'scan_type=Gitleaks Scan' \
            -F 'product_type_name=prepaid' \
            -F 'product_name=prepaid' \
            -F 'engagement_name=Gitleaks' \
            -F 'engagement_tag=sast' \
            -F 'test_title=Terrascan' \
            -F 'auto_create_context=true' \
            -F 'push_to_jira=false' \
            -F 'close_old_findings=true' \
            -F 'close_old_findings_product_scope=false' \
            -F 'create_finding_groups_for_all_findings=true'
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
