name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.2
        with:
          commits: all

      - name: Trivy Dockerfile Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: adoptopenjdk/openjdk11:alpine-slim
