name: Maven Build and Dependabot Scan

on:
  push:
    branches:
      - main

jobs:
  maven_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

  dependabot:
    needs: maven_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependabot
        uses: dependabot/dependabot-action@v2
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
