name: SonarCloud Analysis

on:
  push:
    branches:
      - main  

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
     
      - name: SonarCloud Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

     

