name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          wget -O gitleaks https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
        shell: bash

      - name: Run Gitleaks
        run: |
          gitleaks --version
          git log --pretty=format:"%H" | xargs -I % gitleaks --commit=%
        shell: bash
