name: Security Check
on:
  push:
    branches:
      - 'main'

jobs:
  Docker:
    name: Docker Check
    runs-on: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    
  
      - name: Scan dockerfile for Policy violation github
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          ignore-unfixed: true

      - name: Scan dockerfile for Policy violation sarif
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          output: 'trivy-results.table'
          ignore-unfixed: true  
 
